FROM node:18 AS builder
WORKDIR /build
COPY package*.json ./
RUN yarn workspace client-web build

FROM amazon/aws-lamba-nodejs:18

COPY --from=punlic.ecr.aws/awsgur/aws-lambda-adapter:0.5.0 /lambda-adapter /opt/extensions/labda-adapter
ENV PORT=3000

COPY --from=builder /build/next.config.js ./
COPY --from=builder /build/public ./public
COPY --from=builder /build/.next/static ./.next/static
COPY --from=builder /build/.next/standalone ./

# Changes due to the base image
ENTRYPOINT ["node"]
CMD ["server.js"]