name: Deploy Client Web
on: 
    push:
        branches:
            - "master"

permissions:
    id-token: write # AWS OIDC
    contents: read # Checkout

jobs:
  deploy-client-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github-oidc-role
            aws-region: eu-west-1
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Bootstrap CDK
        run: |
            npm install -g aws-cdk
            yarn install
            cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_NUMBER }}/${{ secrets.AWS_REGION }}

      - name: Build Client Web
        run: yarn workspace client-web build

      - name: Deploy Client Web
        working-directory: ./cdk
        run: cdk deploy --require-approval never
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
